name: Deploy

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
  REGION: us-central1
  CPU: 1
  MEMORY: 256Mi
  MAX_INSTANCES: 10
  DESCRIPTION: ${{ secrets.DESCRIPTION }}

jobs:
  deploy-to-cloud-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build and Push Container
        run: |-
          docker build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }} .
          docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ${{ env.SERVICE_NAME }}
          image: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          region: '${{ env.REGION }}'
          flags: '--cpu ${{ env.CPU }} --memory ${{ env.MEMORY }} --max-instances ${{ env.MAX_INSTANCES }} --allow-unauthenticated'
          env_vars: 'DESCRIPTION=${{ env.DESCRIPTION }}'

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
